/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'model' : string,
  'year' : number,
  'vinNumber' : string,
  'price' : number,
  'isForSale' : boolean,
  'batteryCapacity' : bigint,
}
export interface CarPreference {
  'color' : string,
  'budget' : number,
  'batteryCapacity' : bigint,
}
export interface CustomerInquiry {
  'userId' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'carVin' : string,
}
export interface InventoryInit {
  'model' : string,
  'year' : number,
  'vinNumber' : string,
  'price' : number,
  'isForSale' : boolean,
  'batteryCapacity' : bigint,
}
export interface Order {
  'purchasePrice' : number,
  'userId' : Principal,
  'orderId' : bigint,
  'timestamp' : bigint,
  'carVin' : string,
}
export interface UserProfile {
  'id' : Principal,
  'preferences' : Array<CarPreference>,
  'registered' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventory' : ActorMethod<[Array<InventoryInit>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInquiry' : ActorMethod<[string, string], undefined>,
  'createOrder' : ActorMethod<[string], bigint>,
  'getAllInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventory' : ActorMethod<[], Array<Car>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAvailability' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];