/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InventoryInit = IDL.Record({
  'model' : IDL.Text,
  'year' : IDL.Nat16,
  'vinNumber' : IDL.Text,
  'price' : IDL.Float64,
  'isForSale' : IDL.Bool,
  'batteryCapacity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerInquiry = IDL.Record({
  'userId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'carVin' : IDL.Text,
});
export const Order = IDL.Record({
  'purchasePrice' : IDL.Float64,
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'carVin' : IDL.Text,
});
export const CarPreference = IDL.Record({
  'color' : IDL.Text,
  'budget' : IDL.Float64,
  'batteryCapacity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'preferences' : IDL.Vec(CarPreference),
  'registered' : IDL.Int,
});
export const Car = IDL.Record({
  'model' : IDL.Text,
  'year' : IDL.Nat16,
  'vinNumber' : IDL.Text,
  'price' : IDL.Float64,
  'isForSale' : IDL.Bool,
  'batteryCapacity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventory' : IDL.Func([IDL.Vec(InventoryInit)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInquiry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InventoryInit = IDL.Record({
    'model' : IDL.Text,
    'year' : IDL.Nat16,
    'vinNumber' : IDL.Text,
    'price' : IDL.Float64,
    'isForSale' : IDL.Bool,
    'batteryCapacity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerInquiry = IDL.Record({
    'userId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'carVin' : IDL.Text,
  });
  const Order = IDL.Record({
    'purchasePrice' : IDL.Float64,
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'carVin' : IDL.Text,
  });
  const CarPreference = IDL.Record({
    'color' : IDL.Text,
    'budget' : IDL.Float64,
    'batteryCapacity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'preferences' : IDL.Vec(CarPreference),
    'registered' : IDL.Int,
  });
  const Car = IDL.Record({
    'model' : IDL.Text,
    'year' : IDL.Nat16,
    'vinNumber' : IDL.Text,
    'price' : IDL.Float64,
    'isForSale' : IDL.Bool,
    'batteryCapacity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventory' : IDL.Func([IDL.Vec(InventoryInit)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInquiry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createOrder' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };